<a href="https://colab.research.google.com/github/ghassenov/ML-notebooks/blob/main/Numpy_lib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy arrays:
1.   allow several mathematical operations
2.   faster operations

In [1]:
import numpy as np

List vs Numpy Time Taken

In [2]:
from time import process_time

time taken by a list

In [3]:
python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time-start_time)

0.0007058749999995229


time taken by a numpy array

In [4]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array +=5
end_time = process_time()
print(end_time-start_time)

0.00017363399999936746


Numpy arrays

In [5]:
l = [1,2,3,4,5]
print(type(l))

<class 'list'>


In [6]:
np_arr = np.array(l)
print(type(np_arr))
# nd array for n dimensional array (similar to a matrice)

<class 'numpy.ndarray'>


In [7]:
#creating a 1 dim array
a = np.array([1,2,3,4])
print(a)
print(a.shape) #4 columns

[1 2 3 4]
(4,)


In [9]:
# 2D array
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape) #two rows and 3 columns

[[1 2 3]
 [4 5 6]]
(2, 3)


In [11]:
c = np.array([[1,2,3,4],[5,6,7,8]],dtype=float) #dtype: data type
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [12]:
#ndim tells the dimension of a numpy array
a = np.array(42) #this is a scalar
b = np.array([1, 2, 3, 4, 5]) #1dim array
c = np.array([[1, 2, 3], [4, 5, 6]]) #
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [13]:
#accessing elements is done with []
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [14]:
#for a 3D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [15]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [16]:
#we can also use array slicing [start:end:step]
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [18]:
#slicing 2D arrays:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


initial placeHolders in numpy arrays

In [19]:
#create a numpy array of zeroes
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
# array of a particular value
z = np.full((3,3),5)
print(z)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [26]:
#create an identity matrix
i = np.eye(3,dtype=int)
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [27]:
#create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.12571749 0.69194845 0.43241676 0.07317539]
 [0.43332631 0.38412057 0.61874153 0.47758785]
 [0.93020235 0.92490378 0.97492609 0.4696685 ]]


In [28]:
#random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[72 38 77 35 57]
 [49 12 11 59 10]
 [15 95 74 24 68]]


In [29]:
#array of evenly spaced values
d = np.linspace(10,30,5) #start,end,number of values
print(d)

[10. 15. 20. 25. 30.]


In [35]:
#array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


Analysing a numpy array

In [36]:
a = np.random.randint(10,100,(3,5))
print(a)

[[30 20 34 70 11]
 [10 80 63 41 69]
 [58 45 16 13 43]]


In [37]:
#shape of the array
print(a.shape)

(3, 5)


In [38]:
#dimension
print(a.ndim)

2


In [39]:
#number of elements
print(a.size)

15


In [40]:
#check the datatype of the values
print(c.dtype)

int64


Mathematical operations in a np array

In [42]:
l = [1,2,3]
l2 = [4,5,6]
print(l+l2)
a = np.array(l)
b = np.array(l2)
print(a+b) #does addition on each elements of the two lists

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [43]:
print(a)
print(b)
print(a*b)

[1 2 3]
[4 5 6]
[ 4 10 18]


Array Manipulation

In [46]:
#transpose
a = np.random.randint(10,20,(3,5))
print(a)
print(a.shape)
t = np.transpose(a)
print(t)
print(t.shape)

[[15 13 19 13 11]
 [12 14 19 11 19]
 [15 17 16 19 16]]
(3, 5)
[[15 12 15]
 [13 14 17]
 [19 19 16]
 [13 11 19]
 [11 19 16]]
(5, 3)


In [47]:
#another method is by using a.T
trans2 = a.T
print(trans2)
print(trans2.shape)

[[15 12 15]
 [13 14 17]
 [19 19 16]
 [13 11 19]
 [11 19 16]]
(5, 3)


In [50]:
#reshaping an array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 0 6]
 [7 8 4]]
(2, 3)


In [51]:
b = a.reshape(3,2) #converts a into a (3,2) array
print(b)
print(b.shape)

[[0 0]
 [6 7]
 [8 4]]
(3, 2)
